### ISSUE TITLE
MIDI recording capable?

### ISSUE THREAD

**Issue by therealkitman** [monocasual/giada#123]
Hi,
I was just experimenting with giada and thought I could record a sequence of notes from my midi keyboard into the midi channel's pianoroll instead of using the mouse to create a sequence.

But I gather the midi in is only for controlling the midi channel and not editing/recording. Is that correct?

Thanks,
Chris.

**Comment by monocasual** [comment]
Hi @therealkitman , you definitely can record MIDI notes into MIDI channels from your keyboard, starting from Giada 0.13.1. MIDI recording is almost identical to [audio recording](https://www.youtube.com/watch?v=L66CA1Umk4w) - arm a channel, press the big "rec" button, play your instrument - you just need MIDI channels instead of sample channels.

**Comment by therealkitman** [comment]
Hi, afraid not. Using 0.13.3 - I start giada and add 1 midi. It is armed but when I click the rec button I get the pop up alert "No channels armed/available for audio recording".

Debug screen shows midi notes being received on channel 0.

Sample recording is ok.

**Comment by monocasual** [comment]
@therealkitman you pressed the 'input recording' button, which is meant for audio. You should click on the other button next to it (the one with the donut icon :smirk: ).

**Comment by therealkitman** [comment]
Oh! Um! Yeah "Action Button". 
My mistake, it works!! Very sorry.
Thank you very much.
