### ISSUE TITLE
i18n request

### ISSUE THREAD

**Issue by trebmuh** [monocasual/giada#156]
Hi, I'm willing to help this software with providing a complete translation of the GUI in French. I've looked quickly in the sources and it seems there is no way to do so currently. Could you please add a gettext support to the source?
If you're doing the magics code-wise, I might certainly be able to help (if needed) browsing the sources to add the needed translatable tags to the strings.

**Comment by monocasual** [comment]
@trebmuh the i18n is one of our top priorities for the 1.0 milestone: https://github.com/monocasual/giada/issues/34.

I'm pretty sure it will be based on external configuration files (i.e. no hardcoded stuff), so that anyone can submit his/her own. No programming skills needed. Thanks for your help!
