### ISSUE TITLE
.configure file missing on first step of build instructions

### ISSUE THREAD

**Issue by ssteinerx** [monocasual/giada#162]
From: https://giadamusic.com/documentation/show/compiling-from-source

The instructions say to do the usual `.configure;make` and so forth, but there's no `.configure` file in a fresh checkout from the `master` branch .

I'm going to stop here as any way I might be able to get a `.configure` to appear is unlikely to exactly duplicate the one being used to "build from source."

I'm trying to build on OS X to chase down a device selection bug, but I'm not going to make a different initial condition to start on that...

**Comment by ssteinerx** [comment]
I decided to go ahead and run `autogen.sh` and so forth and was able to make a configuration file, installed all the missing libs, etc.  Even wrote an as yet unpublished blog post about it.

So now it's built and seems to have installed itself at `/usr/local/bin/giada`.  

Even runs!

Until I go to configure...then boom.  Separate bug filed.

**Comment by monocasual** [comment]
Good point @ssteinerx , I think we should better clarify that: 

* https://giadamusic.com/documentation/show/compiling-from-source is for compiling the code inside the tar.gz you download from the site: no autogen.sh needed here;

* https://www.giadamusic.com/documentation/show/development-git-setup is for compiling the code you check out from GitHub: autogen.sh is needed here, in order to prepare the build environment.
