### ISSUE TITLE
windows ui does not feel intuitive

### ISSUE THREAD

**Issue by beppe9000** [monocasual/giada#167]
some first use suggestions/problems using giada on windows server 2016

maybe you could add tooltips that describe each button?

is there a chance the native file opener could be used to open files from disk? when I double click a drive such as `C:\` giada gives an error that makes me think it is trying to load the folder.

also the tab titles in the settings window are only shown when selected

**Comment by monocasual** [comment]
Hi @beppe9000 , we have tooltips somewhere in our road map, which is of course a good suggestion to improve usability.

File browser: we need a custom one, since in the near future we will add audio preview for the selected file (you can't do that with a native file opener).

Tab titles: unfortunately it looks like a limitation of our GUI library (FLTK). I will personally look into this one in a [separate issue](https://github.com/monocasual/giada/issues/168).

**Comment by monocasual** [comment]
Addendum: could you please paste here the error when you try to browse `C:\` drive?

**Comment by tay10r** [comment]
@monocasual It may help to starting working at supporting multiple GUI frameworks. It would require some heavy compartmentalization, but would probably improve the code quality significantly. I would be happy to support a Qt interface (Qt is under GPL for non-commercial use.)

**Comment by monocasual** [comment]
@tay10r honestly I think FLTK is doing its job pretty efficiently so far, although there's a lot of room for improvement in our UI code quality. What really scares me is having multiple "official" GUI frameworks for a single app (maintenance nightmare?). 
However, we are brainstorming on [this](https://github.com/monocasual/giada/issues/171): a set of (possibly language-agnostic) API or, in other words, a way to separate the model from the view. Such feature would pave the way for custom UI implementations, including a mobile version and of course better code separation as you suggested. Feedback is welcome :wink:

**Comment by beppe9000** [comment]
hey i'm still here :) The error happened when I double-clicked to navigate the folder tree to load a project. If I tried to save double-clicking wouldn't do anything at all.

This is the error:

![image](https://user-images.githubusercontent.com/6625123/39421265-8f57dacc-4c68-11e8-9014-faf229b2a961.png)

<hr>

About file opening dialog extensibility have a read of the following article. Altought it's C# it should point you in the right direction.
https://www.codeproject.com/Articles/19566/Extend-OpenFileDialog-and-SaveFileDialog-the-easy

**Comment by tay10r** [comment]
@monocasual I have no experience with FLTK but I'm sure that since you got this far with giada that it probably works pretty well. I don't think it would be a maintenance nightmare by supporting multiple GUIs, once you have a solid MVC pattern established. The only reason I bring it up in the first place is that some people seem to prefer the subtle differences in the way these frameworks appear. Having said that, I think it's a little too early to think about that. I think I might have gotten ahead of myself!

**Comment by tblrchstr** [comment]
Tooltip boxes will be addressed here: https://github.com/monocasual/giada/issues/207

Unreadable config tabs have been fixed in 0.14.6.

An improved and smarter/more usable file browser will be discussed here: https://github.com/monocasual/giada/issues/211
