### ISSUE TITLE
First N frames are cut off when playing a sample through Action Editor

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#248]
As seen in the picture below for a sine wave @ 440 Hz. The problem doesn't occur if the sample is triggered manually. 

![t](https://user-images.githubusercontent.com/39955275/57968963-a6e80680-7971-11e9-847c-0a1308cddd2f.png)

**Comment by tomek-szczesny** [comment]
For the sake of tracking down the bug, the picture shows a 440Hz sine wave (@96 kHz?) with first 27 samples zeroed. I'd check
- if the samples are zeroed or is the first one repeated, because right now we can't be sure,
- If "N" is always 27, or does it change with sampling rate, CPU load, or anything else.

**Comment by monocasual** [comment]
Fixed in development branch (`solid-arch`).

**Comment by monocasual** [comment]
Branch merged, fixed.
