### ISSUE TITLE
Your soundcard isn't configured correctly. Check the configuration and restart Giada.

### ISSUE THREAD

**Issue by sergionexus** [monocasual/giada#360]
This message appears when I run the app. Neither ALSA or Pulseaudio works. But when I select Jack and restart, the app doesn't run. I must delete the ".giada" folder in order to be able to run the app again, but with the same error message. If I run it trough the console it says "Segmentation fault  ('core' generated)".

My system is Manjaro KDE, kernel 5.6.16, jack2. Giada version 0.16.2

I enabled the log to file, but giada.log appears empty!. I don't know what to do next.

**Comment by monocasual** [comment]
Hey @sergionexus , I'm pretty sure you are using a sound card with mono input: is that the case? If so, this bug has been fixed in the development version (#119) and will be released soon.

**Comment by sergionexus** [comment]
I'm using the integrated soundcard of my mother board, an ALC887, if this info is usefull for you.

Thanks for the fast response.

**Comment by monocasual** [comment]
Quick test: run Giada, open the Configuration Panel, locate the Input device drop-down menu and press the button on the right. A new window will pop up reporting the device information: could you please paste that content here?

**Comment by sergionexus** [comment]
I can't select anything...
![Screenshot_20200714_163216](https://user-images.githubusercontent.com/28978954/87438487-e18a1500-c5ef-11ea-9dfb-96a24bbe6e19.png)

**Comment by sergionexus** [comment]
Ok, selecting ALSA and my device, it shows this:
![Screenshot_20200714_164030](https://user-images.githubusercontent.com/28978954/87439243-d683b480-c5f0-11ea-82c5-a9bb91f04b1c.png)

**Comment by sergionexus** [comment]
Ok. I choose ALSA and the imput and output ALSA device, save and restart. After doing this now I can select Jack. I'm going to make some test and comment again.

Thanks for your dedication and patience.

**Comment by sergionexus** [comment]
Well, I solve the problem. In case it can help someone with the same problem, here are the steps I did:

1.- Use "yay" or "octopy" to install "giada-git" from the Arch User Repository (AUR)
2.- Download the AppImage version of Giada from the web
3.- Delete the ".giada" folder in /home/your_user_name/ if exist
4.- Run the AppImage version of Giada (I need it because the installed version fails creating the ".giada" folder)
5.- Go to configuration and select ALSA. Save and restart Giada
6.- Go to config and select the input and output soundcard under ALSA. Be sure to select the correct outputs and inputs channels (in my case: "1+2" in the output section, and "1" in the input section. Save and restart Giada.
7.- Open the installed version of Giada, NOT the AppImage version
8.- Go to config and select Jack. Save and restart.
9.- Now you can choose audio output device (I select "system"), audio input device, and double check that number of channels on input and output are OK. ("1+2" outputs, "1" inputs). Select the MIDI, etc... Save and restart.

Now Giada is working.

Thanks for all, and keep going.

**Comment by tomek-szczesny** [comment]
I am running into a very similar problem, except I don't know how to solve it. Ubuntu Studio Eoan.
(I eventually solved my problem, explanation at the very bottom).

Once I compiled Giada from the source, the application runs with stdout:
```
[init] Giada 0.16.4
[init] Build date: Jul 23 2020
[init] Dependencies:
[init]   FLTK - 1.3.4
[init]   RtAudio - 5.1.0
[init]   RtMidi - 3.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.7.3
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '/home/mctom/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
```
So far so good, this is to be expected.

If I select any Sound System (JACK), upon clicking "Save" button Giada crashes (gdb output):

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Nie ma takiego pliku ani katalogu.
(gdb) c
Continuing.

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.
```
(No such file nor directory)

This can be repeated indefinitely. _.giada_ directory is not created.

I ran current AppImage, set JACK system and save. Upon clicking on Config button again, program disappears. 
I ran AppImage again, set JACK system, saved, and closed Giada immediately. A _.giada_ dir has been created, with _giada.conf_ inside:

`
{"action_editor_grid_on":0,"action_editor_grid_val":0,"action_editor_h":480,"action_editor_w":640,"action_editor_x":192,"action_editor_y":144,"action_editor_zoom":100,"browser_h":480,"browser_last_path":"","browser_last_value":0,"browser_position":0,"browser_w":640,"browser_x":192,"browser_y":144,"buffer_size":1024,"channels_in":-1,"channels_out":-1,"chans_stop_on_seq_halt":false,"envelope_editor_h":40,"header":"GIADACFG","input_monitor_default_on":false,"last_midimap":"","limit_output":false,"log_mode":4,"main_window_h":510,"main_window_w":816,"main_window_x":104,"main_window_y":129,"midi_in":false,"midi_in_action_rec":0,"midi_in_beat_doble":0,"midi_in_beat_half":0,"midi_in_filter":-1,"midi_in_input_rec":0,"midi_in_metronome":0,"midi_in_rewind":0,"midi_in_start_stop":0,"midi_in_volume_in":0,"midi_in_volume_out":0,"midi_input_h":480,"midi_input_w":640,"midi_input_x":0,"midi_input_y":0,"midi_port_in":-1,"midi_port_out":-1,"midi_sync":0,"midi_system":2,"midi_tc_fps":25.0,"midimap_path":"","patches_path":"","piano_roll_h":422,"piano_roll_y":-1,"plugin_chooser_h":480,"plugin_chooser_w":640,"plugin_chooser_x":0,"plugin_chooser_y":0,"plugin_list_x":0,"plugin_list_y":0,"plugin_sort_method":0,"plugins_path":"","rec_trigger_level":-10.0,"rec_trigger_mode":0,"resample_quality":0,"sample_action_editor_h":40,"sample_editor_grid_on":0,"sample_editor_grid_val":0,"sample_editor_h":480,"sample_editor_w":640,"sample_editor_x":0,"sample_editor_y":0,"samplerate":44100,"samples_path":"","sound_device_in":-1,"sound_device_out":0,"sound_system":1,"treat_recs_as_loops":false,"velocity_editor_h":40}`

AppImage won't run again, it won't even show up. Same with my own compiled version. gdb returns something like this:

```
(...)
[init]   JSON for modern C++ - 3.7.3
[midiMapConf::init] scanning midimaps directory '/home/mctom/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
[New Thread 0x7ffff5960700 (LWP 25852)]
[New Thread 0x7ffff581f700 (LWP 25853)]

Thread 3 "giada" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7ffff581f700 (LWP 25853)]
__libc_read (nbytes=4, buf=0x7ffff581ec40, fd=6) at ../sysdeps/unix/sysv/linux/read.c:26
26      ../sysdeps/unix/sysv/linux/read.c: Nie ma takiego pliku ani katalogu.
```


---

I solved my problem eventually. IT turns out that PulseAudio was standing on a way and Jack couldn't connect to the interface properly. Once I killed pulseaudio and made a few more attempts, it works great right now.

@sergionexus probably had a similar issue with Jack wrestling PulseAudio or whatever. He might have also done something in the meantime that he assumed is not important.

Anyway, I guess there might be a more graceful way to notify a user about this problem. Maybe some sort of initial check?
