### ISSUE TITLE
freezes when closing

### ISSUE THREAD

**Issue by sezanzeb** [monocasual/giada#371]
![image](https://user-images.githubusercontent.com/28510156/88455792-b49ff280-ce78-11ea-8ca1-d258d681ac4a.png)

it just froze. Can't reproduce it again.

**Comment by tomek-szczesny** [comment]
@sezanzeb, I think this is hardly enough information to work on it. If it happens next time, please provide more information: Your OS, sound system, and what you think might be linked to such behavior.
Also, it might be a good idea to turn on debug messages log in config window, "Misc" tab.

Thanks!

**Comment by Kirtai** [comment]
This happens to me on EndeavourOS every time I try to close it. It happens with both the aur and the flatpak version (0.22.0)

The problem seems to be when you set the audio out to Jack on a system running Pipewire.

I get an endless amount of the following error while running:
```
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
```
and a freeze on trying to exit.
