### ISSUE TITLE
Remove WITH_VST conditional compilation

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#415]
`WITH_VST` was added when shipping the VST SDK was not allowed due to licensing issues. Now that VST3 SDK is open source I assume we can get rid of the conditional compilation, and ship Giada compiled with VST3 support by default.
Deprecated VST2 support can still be optionally enabled at compile time.

**Comment by tomek-szczesny** [comment]
Sounds perfectly reasonable. Is there any reason to keep VST2 support though? I assume VST3 is backward compatible.

**Comment by monocasual** [comment]
Good question. Apparently it's not backward compatible for hosting: Giada compiled in VST3-only mode doesn't scan VST2.x plugins at all.

**Comment by tomek-szczesny** [comment]
So I understand that Giada should always compile WITH_VST,  but a new flag will be introduced to compile VST2 along with VST3?
I'm not experienced with VSTs at all, but I'm worried whether these two can work at the same time at all.

**Comment by monocasual** [comment]
> So I understand that Giada should always compile WITH_VST, but a new flag will be introduced to compile VST2 along with VST3?
> I'm not experienced with VSTs at all, but I'm worried whether these two can work at the same time at all.

JUCE already supports both: you can have VST2.x and VST3 enabled at the same time (along with other formats such as AudioUnits and more).

Currently CMakeLists.txt provides 2 parameters: `WITH_VST2` and `WITH_VST3`. If one of them is enabled, the `WITH_VST` macro is defined to enable VST compilation. My idea is to:
* get rid of `WITH_VST3`: VST3 will be enabled by default
* get rid of `WITH_VST` to always compile with VST3 support 
* keep `WITH_VST2` in case someone wants VST2.x support.

**Comment by tomek-szczesny** [comment]
Unless there is no risk that VST SDK gets closed-source at some point ;) I guess this makes sense. I was just worried for a moment that we'd have to add WITH_VST back at some point, that'd be terrible. :)

**Comment by musicinmybrain** [comment]
In Fedora Linux, we have to not only build `giada` without VST3 support, but also strip out the bundled VST3 SDK and JUCE code from the source tarball before using it, because the [additional trademark-related conditions](https://developer.steinberg.help/display/VST/Steinberg+VST+usage+guidelines) imposed [on top of the GPLv3](https://developer.steinberg.help/pages/viewpage.action?pageId=9797944) are [too restrictive](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/Y2U75V7PNDPZTUDVVBCNA5OPTHSPS6YE/#FMFIZU22AP36J3DOUVCXUPHQ3MNDN5P6) for us to safely redistribute the code.

So as the maintainer of the `giada` package in Fedora Linux, I really appreciate the `WITH_VST3` option, because if it wasn’t there I would have to either patch it back in or retire the package from the distribution.

**Comment by gvnnz** [comment]
Thanks @musicinmybrain , interesting reads. Let's keep VST support optional.
