### ISSUE TITLE
unable to compile missing cpp file

### ISSUE THREAD

**Issue by prototypen9e** [monocasual/giada#431]
im trying to compile this on slackware64 its unable to compile due to a missing baseButton,cpp file 
pes.cpp' || echo './'`src/gui/elems/basics/boxtypes.cpp
mv -f src/gui/elems/basics/.deps/giada-boxtypes.Tpo src/gui/elems/basics/.deps/giada-boxtypes.Po
make: *** No rule to make target 'src/gui/elems/basics/baseButton.cpp', needed by 'src/gui/elems/basics/giada-baseButton.o'.  Stop.

**Comment by dvzrv** [comment]
@monocasual This concerns version 0.17.0 btw. While it's nice to now have a basic cmake setup included it is not complete (no tests, no install target) and can not be used instead of the autotools based setup.

@prototypen9e It seems the files are not required anymore. You can remove the entries with `sed '/baseButton/d' -i Makefile.am`.

**Comment by monocasual** [comment]
@prototypen9e are you building with cmake or autotools? We are gradually moving all the autotools functionalities to cmake, something must have slipped through the cracks. 

@dvzrv you said it's unusable because of the missing install target, the tests or both?

**Comment by dvzrv** [comment]
@monocasual this is an issue with the autotools setup.

The cmake setup is not really usable if one wants to run tests (I think that still requires autotools to build the tests anyways?), as cmake does not create a test target (maybe I missed something?).
Not having an install target is also not so great, as it means more manual intervention, which is why I stuck with the autotools setup for now.

**Comment by monocasual** [comment]
@dvzrv I'm planning to include tests & install target in the cmake setup (i.e. issue #422) in the next release 0.17.1. Thanks for the explanation and your patience!
