### ISSUE TITLE
Midimaps missing in Master Branch

### ISSUE THREAD

**Issue by blablack** [monocasual/giada#51]
Hello,

The midimaps are missing from the master branch.
the midimaps folder contains the ones that come with Giada.

In addition the Makefile points to them.

c.f. https://github.com/blablack/giada/tree/midi-lightning

**Comment by blablack** [comment]
Tested further with the folder copied manually - Giada still cannot find them.

I went through the code quickly, it looks like the fetching of midi maps is completely different, and it doesn't seem to be possible to browse manually for a map.

Can you tell me if it is on purpose?

**Comment by blablack** [comment]
Ok, I finally figured they needed to be in the .giada folder but:
- I still couldn't find a way to browse manually and load my own maps. That is missing for user friendliness.
- the combo box in the midi config just display the raw filename, I think I use to read the info from the map and display that in the combo box
- the way giada reads from .giada is not great for one reason, maps cannot be provided as part of the installation package. For Linux I used to install them in /usr/share/giada/midimaps
- the launchpad map I created is not in the source code

Overall it's not very user friendly at the moment. In my branch giada would come with pre-installed maps and I could browse for new ones through the GUI. Now I had to mess about for a while to make it work, figure out where I was supposed to copy things.

What do you think?

**Comment by monocasual** [comment]
Hi blablack,

Thanks for your feedback!

> I still couldn't find a way to browse manually and load my own maps. That is missing for user friendliness.

> the way giada reads from .giada is not great for one reason, maps cannot be provided as part of the installation package. For Linux I used to install them in /usr/share/giada/midimaps

We decided not to ship midimaps as part of the package, due to its double-maintenance effort. Therefore we created the [official midimaps repo](https://github.com/monocasual/giada-midimaps). You just grab the zip from there and drop the content in `~/.giada` (on Linux) . That's it.

Devs can make pull requests there if they want to submit a new midimap (end users can do the same on the forum as well, there's a mirrored thread there). 

> the launchpad map I created is not in the source code

You can find it in the repo mentioned above.

> the combo box in the midi config just display the raw filename, I think I use to read the info from the map and display that in the combo box.

Maps reading algorithm was simplified, that's a small regression we will fix very soon.
